### ISSUE TITLE
Dot-stuffing occurs in the middle of a line across buffer boundaries

### ISSUE THREAD

**Issue by Allon-Guralnek** [jstedfast/MailKit#788]
**Describe the bug**
When there's a dot character as the first character of a 4096 byte buffer (used to write to SMTP streams) but not after a newline (which was somewhere near the end of the previous buffer), when it passes through the dot-stuffing `SmtpDataFilter` class, the dot at the beginning of the buffer is always considered to be the first character of the line, even when it is not (just happens to be at the beginning of that sliced buffer) and the dot is doubled. This should only happen if the dot is the the first character after a newline, not when it's the first character in the buffer, which could be in the middle of a line (like in the repro below). I think the root cause is that the line breaking and dot stuffing occur in different stages, so one can cause buffer-newline misalignment which otherwise wouldn't occur because 4096 is divisible by 78.

Or at least, that's what I think is the issue from debugging the MailKit code.

**To Reproduce**
Replace `"sender@gmail.com"`, `"recipient@gmail.com"`, `"GmailUsername"`, `"GmailPassword"` with appropriate values (the issue also happens with a different email server, e.g. Postfix that uses commercial email provider, but Gmail repros it just fine).

```csharp
var mailMessage = new MimeMessage
{
	Subject = "Bad dot-stuffing at buffer borders",
	From = { new MailboxAddress("sender@gmail.com") },
	To = { new MailboxAddress("recipient@gmail.com") },
	Body = new BodyBuilder { HtmlBody = new string('x', 4096) + ".hello" }.ToMessageBody()
};

using (var smtpClient = new SmtpClient())
{
	await smtpClient.ConnectAsync("smtp.gmail.com", 587, MailKit.Security.SecureSocketOptions.StartTls);
	await smtpClient.AuthenticateAsync("GmailUsername", "GmailPassword");
	await smtpClient.SendAsync(mailMessage);
}
```

**Expected behavior**
Email body should end with **xxxxxxx.hello**

**Actual behavior**
Email body ends with **xxxxxxx..hello**

**Comment by jstedfast** [comment]
Which version of MailKit are you using?

**Comment by jstedfast** [comment]
Never mind, I thought your test case had the previous buffer *end* with a new-line and the unit tests I wrote up worked so I got confused. Then I re-read and saw that it probably wouldn't have ended on a new-line, so wrote up a test for that and immediately spotted the problem.

All fixed in git master now.

**Comment by Allon-Guralnek** [comment]
Thanks! I just tested it and it seems to have solved the issue. Didn't figure out what `bol` means quite yet.

When do you expect the NuGet release with this fix to be published?

**Comment by jstedfast** [comment]
`bol` means Beginning-of-Line

**Comment by jstedfast** [comment]
I was hoping not to do another release until January. I *just* pushed 2.1.1 yesterday and I prefer to go 2 months between releases. It takes me hours to make a release so it really cuts into my free time :-(

**Comment by jstedfast** [comment]
Since there's already 1 other fix as well, I can look at making a new release in either late December (the week after Christmas) or early January. I probably won't have enough time to spare until then.

Thanks again for digging into this bug report as much as you did and providing a test case. You have no idea how much I appreciate it when people do that. It really saves me a lot of time and effort.

**Comment by Allon-Guralnek** [comment]
Okay, I just published the current master as a prerelease package to our own internal NuGet server for the interim. Yay for open source 😁

**Comment by jstedfast** [comment]
How are you automating it? I know you can have CI systems like AppVeyor generate (and even publish?) the nugets, but due to the fact that MimeKit and MailKit also have Xamarin and WindowsUniversal targets (and not just .NET45/.NETStandard), AppVeyor doesn't support those so it's a pain.

**Comment by Allon-Guralnek** [comment]
We use TeamCity and it can run arbitrary scripts, so anything can be automated there. Not sure about AppVeyor. But it doesn't have to be a public-facing CI system, it can be a free TeamCity install on some minimal Azure box that only you have access to. But make it a single-click affair, like it should be. For example, we use [Paket](https://fsprojects.github.io/Paket/) instead of NuGet client and they have a very large public user-base, yet they sometimes release two or three versions a day. Every little fix get's a package published, the whole thing's automated and worry-free.

Even if you do release only once every two months, assuming it takes you hours to make a release like you said, and you've made 70 releases... how much time have you spent just doing the repetitive and rather dull work of preparing releases? It shouldn't take more than a couple of hours to completely automate it, and the only thing that'll need to be done manually is composing release notes (which are quite easy to do when only have one little fix each release).

Not saying you should do it, just throwing an idea out there. Wouldn't want you to waste your free time doing releases rather than the much more important work like maintaining and improving these great libraries.

**Comment by jstedfast** [comment]
Yea, I definitely need to find a simpler solution. Thanks.

**Comment by AndrewGretton** [comment]
@jstedfast have you looked at Azure Devops for automation of builds and releases? It works with the Xamarin/WPA builds out of the box (I just tested it with a sample build of Mailkit). Nuget publishing is a first class citizen in the pipeline too, and it's all free for open source projects.

Happy to help set up a proof of concept if you're interested.

**Comment by jstedfast** [comment]
I haven't yet, no, but I would be interested if you have a proof-of-concept setup for this.

**Comment by AndrewGretton** [comment]
Naively, I think it's probably as simple as [this example I just made on Azure Devops](https://dev.azure.com/andrewgretton/Mailkit-Demo/_build/results?buildId=22&_a=summary&view=results). For every commit to the main repo, it will

* Restore nuget packages
* Build `mailkit.sln` in Release config
* Pack up a nupkg package, which then becomes available on the summary tab in the "build artifacts" section. It includes all target platforms including Xamarin, UWP, etc.

Next steps would be

* Make the tests + opencover work part of the build process (I've just started on this but ran out of time tonight)
* Automate the publish to nuget.org push if a change is detected to `mailkit.nuspec`
    * Alternatively create a separate release job just for the nuget.org push
* Automate the docs generation (another build step/build artifact output)

All of the above are doable, I just haven't jumped in with both feet yet. Is the journey from git commit to actually getting a nupkg file, the bit that's causing you pain when releasing? If so, tada :) If not, what else can I show you?

If you went down this route, you'd obviously want [your own (free) Azure Devops subscription](https://azure.microsoft.com/en-gb/pricing/details/devops/azure-devops-services/) to manage it yourself, though you can of course invite users. I'd love to help pitch in if you do pick this option.

**Comment by jstedfast** [comment]
Mind sharing your yml script? I can't seem to view it on your devops page.

**Comment by AndrewGretton** [comment]
I cheated and used the visual designer to create my build; but exported as YAML it is as follows. Note that I didn't get the test results wired up yet; but the tests do run.

```
resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: msbuild
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.2'
  inputs:
    versionSpec: 4.9.2
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: Mailkit.sln
- task: MSBuild@1
  displayName: 'Build solution MailKit.sln'
  inputs:
    solution: MailKit.sln
    platform: 'Any CPU'
    configuration: Release
    msbuildArguments: '/t:Rebuild'
    clean: true
    maximumCpuCount: true
- powershell: '.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[MailKit]* -[UnitTests]* -[submodules]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/framework:net-4.5 /noshadow /domain:single /out:UnitTests\bin\Release\TEST-UnitTests.xml UnitTests\bin\Release\UnitTests.dll" -output:opencover.xml'
  displayName: 'Run tests'
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: nuget/mailkit.nuspec
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Nuget package'
  inputs:
    ArtifactName: 'Nuget package'
```
